<a href="https://colab.research.google.com/github/Miguel-EMC/Tarea-10/blob/main/Tarea10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Definir las matrices
A_a = np.array([[2, -3], [3, -1]])
B_a = np.array([[1, 5], [2, 0]])

A_b = np.array([[2, -3], [3, -1]])
B_b = np.array([[1, 5, -4], [-3, 2, 0]])

A_c = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
B_c = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])

A_d = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
B_d = np.array([[1, -2], [-4, 1], [0, 2]])

# Multiplicar las matrices
result_a = np.dot(A_a, B_a)
result_b = np.dot(A_b, B_b)
result_c = np.dot(A_c, B_c)
result_d = np.dot(A_d, B_d)

# Mostrar los resultados
result_a, result_b, result_c, result_d


(array([[-4, 10],
        [ 1, 15]]),
 array([[ 11,   4,  -8],
        [  6,  13, -12]]),
 array([[ -1,   5,  -3],
        [  3,   4, -11],
        [ -6,  -7,  -4]]),
 array([[ -2,   1],
        [-14,   7],
        [  6,   1]]))

In [ ]:
# Definir las matrices
A = np.array([[4, 2, 6], [3, 0, 7], [-2, -1, -3]])
B = np.array([[1, 2, 0], [2, 1, -1], [3, 1, 1]])
C = np.array([[1, 1, -1, 1], [1, 2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]])
D = np.array([[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 1, 0], [5, 4, 1, 1]])

# Calcular los determinantes
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)

# Verificar si las matrices son no singulares y calcular la inversa si lo son
inv_A = np.linalg.inv(A) if det_A != 0 else None
inv_B = np.linalg.inv(B) if det_B != 0 else None
inv_C = np.linalg.inv(C) if det_C != 0 else None
inv_D = np.linalg.inv(D) if det_D != 0 else None

det_A, det_B, det_C, det_D, inv_A, inv_B, inv_C, inv_D


(0.0,
 -8.000000000000002,
 0.0,
 28.00000000000001,
 None,
 array([[-0.25 ,  0.25 ,  0.25 ],
        [ 0.625, -0.125, -0.125],
        [ 0.125, -0.625,  0.375]]),
 None,
 array([[ 0.25      ,  0.        ,  0.        ,  0.        ],
        [-0.21428571,  0.14285714, -0.        , -0.        ],
        [ 0.10714286, -1.57142857,  1.        , -0.        ],
        [-0.5       ,  1.        , -1.        ,  1.        ]]))

In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([
    [1, -1, 2, -1],
    [1, 0, -1, 1],
    [2, 1, 3, -4],
    [0, -1, 1, -1]
])

# Constant vector b1 for System 1
b1 = np.array([6, 4, -2, 5])

# Constant vector b2 for System 2
b2 = np.array([1, 1, 2, -1])

# Solve the systems
x1 = np.linalg.solve(A, b1)
x2 = np.linalg.solve(A, b2)

x1, x2


(array([ 3., -6., -2., -1.]), array([1., 1., 1., 1.]))

In [ ]:
import numpy as np

# Definir las matrices para el sistema a
A_a = np.array([[1, 0, 0],
                [2, 1, 0],
                [-1, 0, 1]])

B_a = np.array([[2, 3, -1],
                [0, -2, 1],
                [0, 0, 3]])

C_a = np.array([2, -1, 1])

# Multiplicar A_a y B_a
AB_a = np.dot(A_a, B_a)

# Resolver el sistema AB_a * X = C_a
X_a = np.linalg.solve(AB_a, C_a)

# Definir las matrices para el sistema b
A_b = np.array([[2, 0, 0],
                [-1, 1, 0],
                [3, 2, -1]])

B_b = np.array([[1, 1, 1],
                [0, 1, 2],
                [0, 0, 1]])

C_b = np.array([-1, 3, 0])

# Multiplicar A_b y B_b
AB_b = np.dot(A_b, B_b)

# Resolver el sistema AB_b * X = C_b
X_b = np.linalg.solve(AB_b, C_b)

X_a, X_b


(array([-3.,  3.,  1.]), array([ 0.5, -4.5,  3.5]))

In [ ]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        L[i][i] = 1
        for j in range(i, n):
            U[i][j] = A[i][j] - sum(L[i][k] * U[k][j] for k in range(i))
        for j in range(i + 1, n):
            L[j][i] = (A[j][i] - sum(L[j][k] * U[k][i] for k in range(i))) / U[i][i]

    return L, U

def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)

    for i in range(n):
        y[i] = b[i] - sum(L[i][j] * y[j] for j in range(i))

    return y

def backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i][j] * x[j] for j in range(i + 1, n))) / U[i][i]

    return x

def solve_lu(A, b):
    L, U = lu_decomposition(A)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x

# Resolución de los sistemas lineales proporcionados:

# a.
A1 = np.array([[2, -1, 1],
               [3, 3, 9],
               [3, 3, 5]])
b1 = np.array([-1, 0, 4])
x1 = solve_lu(A1, b1)
print("Solución para el sistema a:", x1)

# b.
A2 = np.array([[1.012, -2.132, 3.104],
               [-2.132, 4.096, -7.013],
               [3.104, -7.013, 0.014]])
b2 = np.array([1.984, -5.049, -3.895])
x2 = solve_lu(A2, b2)
print("Solución para el sistema b:", x2)

# c.
A3 = np.array([[2, 0, 0, 0],
               [1, 1.5, 0, 0],
               [0, -3, 0.5, 0],
               [2, -2, 1, 1]])
b3 = np.array([3, 4.5, -6.6, 0.8])
x3 = solve_lu(A3, b3)
print("Solución para el sistema c:", x3)

# d.
A4 = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
               [-4.0231, 6.0000, 0, 1.1973],
               [-1.0000, -5.2107, 1.1111, 0],
               [6.0235, 7.0000, 0, -4.1561]])
b4 = np.array([17.102, -6.1593, 3.0004, 0])
x4 = solve_lu(A4, b4)
print("Solución para el sistema d:", x4)


Solución para el sistema a: [ 1.  2. -1.]
Solución para el sistema b: [1. 1. 1.]
Solución para el sistema c: [ 1.5  2.  -1.2  3. ]
Solución para el sistema d: [2.9398512  0.0706777  5.67773512 4.37981223]
